SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS meeting_room_booking;

USE meeting_room_booking;

SELECT * FROM users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
);

TRUNCATE TABLE users;